# Site settings
title:
email:
description: > Santtu Pyykkönen, Geospatial IT expert - Online portfolio.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email: p.santtuvp@gmail.com
facebook_username:
twitter_username: "@santtuvp"
github_username: santtuvp
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown

#Plugins
gems:

# Google services
google_analytics: UA-82392403-5
